language: node_js
node_js:
- 10
os:
- linux
cache:
  directories:
  - node_modules
stages:
- test
- pack
- name: deploy
  if: "(type = push) AND branch =~ ^(master|v\\d+\\.\\d+)$"
jobs:
  include:
  - stage: test
    script:
    - node --version
    - npm --version
    - echo "Testing Started ..."
    - npm test
    - echo "Testing Finished."
  - stage: pack
    script:
    - echo "NPM Pack Testing Started ..."
    - npm version
    - "./scripts/generate-version.sh"
    - npm run test:pack
    - echo "NPM Pack Testing Finished."
  - stage: deploy
    script:
    - echo "NPM Deploying Started ..."
    - npm version
    - "./scripts/generate-version.sh"
    - "./scripts/package-publish-config-tag.sh"
    - npm run dist
    - echo "NPM Building Finished."
    deploy:
      provider: npm
      email: suchang@juzi.bot
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        all_branches: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always
    on_failure: always
    on_start: never
  email:
    on_success: change
    on_failure: change
deploy:
  api_key:
    secure: q1LRcQIXq9phYW82ABNCr6bwSGKsG0j7frNzXvIOe0EJ7iJnXRxQBG1c8oVACbOkT0QibVQJMlmjPlB2c6SQSUSlQbbx73E8JKH/vSKtWHWMgdGCsE3xHP8Pe/CTmncD8nLWW9w+GSeHkTT4d3ZXS85E5HjglaC7+IJFg0OhUQQsVchcSxYIVBuPoJVtfh448kGUgpigSyqNGIB753+ZNiavJ2wCSoMMyC8A2OKeoEJ4iMyUQH6cyMtE81ELbsqQ/rYfHWjlfExqkofePP/C0SoUSKqwHEqMkeqpUQ6EwcERIFMGuTbwuK0wwhAwRrx2TUYfEqjI5SBsNr4NvcV89E6eAm1sLfi+sJbhh/5i5RIkIT/l4zcHIMwEL5h7xJ85iu+lVrkv/tcv2msbTcJuh3Khi9guYDHW/4x7NKtqQ476jYohbFFFyWFSBb4mOFcyYuIoQM3YNEAF7ncqGlnAorwB78ic6yzA20t1idq2NOgKkG3etD98KHP6RN+vj9QGZeYaBScCiEQlzxirL12WnDf3oLTcVePDYXZhe/IebznaBDPIVGH6Rz6AA7Mcski08NK1uzWLwLrhIIyB0yap0j3YeJgH1beSm1ghP9GZkROn2tEb+Oeljc9IuQpxM4Z7uLZDqGfFi2u90COWEJOo6GourSkvwImqwsLarEqAJR4=
